In [62]:
import numpy as np
import csv
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error
import matplotlib.pyplot as plt
from datetime import datetime

In [36]:
with open('train.csv') as csv_file: # Make sure to replace 'train.csv' with your actual file path
    readCSV = csv.reader(csv_file)
    next(readCSV, None) # Skip the title of the csv file
    data1 = []
    for row in readCSV:
        data1.append(row)
print(len(data1))

6500


In [142]:
# with open('train.csv') as csv_file: #/Users/thanakornpongritsakda/Documents/Programming-SCMA-249/50_Startups.csv (path)
#     readCSV = csv.reader(csv_file)
#     next(readCSV, None) #skip the title of the csv file
#     data1 = []
#     for row in readCSV:
#         data1.append(row)
        
with open('train.csv') as csv_file: # Make sure to replace 'train.csv' with your actual file path
    readCSV = csv.reader(csv_file)
    next(readCSV, None) # Skip the title of the csv file
    data1 = []
    for row in readCSV:
        if "" not in row:  # This checks if 'NA' is not present in the row
            data1.append(row)

        
data1 = np.array(data1)
Artist_reputation = np.array(data1[:,2], dtype = np.float64)
Height = np.array(data1[:,3], dtype = np.float64)
Width = np.array(data1[:,4], dtype = np.float64)
Weight = np.array(data1[:,5], dtype = np.float64)
Material = np.array(data1[:,6])
Price_of_sculpture = np.array(data1[:,7], dtype = np.float64)
Base_shipping_price = np.array(data1[:,8], dtype = np.float64)
International = np.array(data1[:,9])
Express_shipment = np.array(data1[:,10])
Installation_included = np.array(data1[:,11])
Transport = np.array(data1[:,12])
Fragile = np.array(data1[:,13])
Customer_information = np.array(data1[:,14])
Remote_location = np.array(data1[:,15])
Scheduled_date = np.array(data1[:,16])
Delivery_date = np.array(data1[:,17])
Customer_location = np.array(data1[:,18])
Cost = np.array(data1[:,19], dtype = np.float64)

# Define a function to convert date strings to datetime objects
def parse_dates(date_str):
    return datetime.strptime(date_str, '%m/%d/%y')  # Adjusted the format to match your dates

# Vectorize the function so it can be applied over numpy arrays
vectorized_parse_dates = np.vectorize(parse_dates)

# Convert the date strings to datetime objects
Scheduled_dates_parsed = vectorized_parse_dates(Scheduled_date)
Delivery_dates_parsed = vectorized_parse_dates(Delivery_date)

# Calculate the difference in days
timeliness_of_a_shipping = (Delivery_dates_parsed - Scheduled_dates_parsed).astype('timedelta64[D]').astype(int)
# Early Shipping: Represented as a negative number
# On-time Shipping: Represented as zero
# Late Shipping: Represented as a positive number

print(data1)
print(Artist_reputation)
print(Height)
print(Width)
print(Weight)
print(Material)
print(Price_of_sculpture)
print(Base_shipping_price)
print(International)
print(Express_shipment)
print(Installation_included)
print(Transport)
print(Fragile)
print(Customer_information)
print(Remote_location)
print(Scheduled_date)
print(Delivery_date)
print(Customer_location)
print(timeliness_of_a_shipping)

[['fffe3900350033003300' 'Billy Jenkins' '0.26' ... '06/03/15'
  'New Michelle, OH 50777' '-283.29']
 ['fffe3800330031003900' 'Jean Bryant' '0.28' ... '03/05/17'
  'New Michaelport, WY 12072' '-159.96']
 ['fffe3600370035003100' 'Laura Miller' '0.07' ... '03/08/15'
  'Bowmanshire, WA 19241' '-154.29']
 ...
 ['fffe3800370037003300' 'Jeffrey Freudenthal' '0.37' ... '03/25/18'
  'New Robert, VT 85335' '872.43']
 ['fffe3600350035003900' 'Daniel Drew' '0.02' ... '03/12/19'
  'Hintonberg, UT 35006' '5037.5']
 ['fffe3700310031003600' 'Vernon Carroll' '0.18' ... '12/05/16'
  'New Christopher, AK 87406' '722.47']]
[0.26 0.28 0.07 ... 0.37 0.02 0.18]
[17.  3.  8. ... 37. 33. 30.]
[ 6.  3.  5. ... 10.  9. 13.]
[4.128000e+03 6.100000e+01 2.370000e+02 ... 1.655100e+04 1.269377e+06
 3.472900e+04]
['Brass' 'Brass' 'Clay' ... 'Brass' 'Stone' 'Brass']
[  13.91    6.83    4.96 ...   28.28 2929.13   46.63]
[16.27 15.   21.18 ... 38.46 69.76 78.25]
['Yes' 'No' 'No' ... 'Yes' 'No' 'No']
['Yes' 'No' 'No' ...

In [86]:
# Clean data

# Create dummy for Material
Brass = np.zeros(len(Material))
Clay = np.zeros(len(Material))
Aluminium = np.zeros(len(Material))
Wood = np.zeros(len(Material))
Marble = np.zeros(len(Material))
Bronze = np.zeros(len(Material))
Stone = np.zeros(len(Material))

for i in range(len(Material)):
    if Material[i] == 'Brass':
        Brass[i] = 1
    elif Material[i] == 'Clay':
        Clay[i] = 1
    elif Material[i] == 'Aluminium':
        Aluminium[i] = 1
    elif Material[i] == 'Wood':
        Wood[i] = 1
    elif Material[i] == 'Marble':
        Marble[i] = 1
    elif Material[i] == 'Bronze':
        Bronze[i] = 1
    else:
        Stone[i] = 1

print(Brass)
print(Clay)
print(Aluminium)
print(Wood)
print(Marble)
print(Bronze)
print(len(Stone))
#print(len(State))

[1. 1. 0. ... 1. 0. 1.]
[0. 0. 1. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
3362


In [104]:
# Clean data for International, Express Shipment, Installation Included, Fragile and Remote Location
International_clean = np.zeros(len(International))
for i in range(len(International)):
    if International[i] == 'Yes':
        International_clean[i] = 1

Express_shipment_clean = np.zeros(len(Express_shipment))
for i in range(len(Express_shipment)):
    if Express_shipment[i] == 'Yes':
        Express_shipment_clean[i] = 1
        
Installation_included_clean = np.zeros(len(Installation_included))
for i in range(len(Installation_included)):
    if Installation_included[i] == 'Yes':
        Installation_included_clean[i] = 1
        
Fragile_clean = np.zeros(len(Fragile))
for i in range(len(Fragile)):
    if Fragile[i] == 'Yes':
        Fragile_clean[i] = 1
        
Remote_location_clean = np.zeros(len(Remote_location))
for i in range(len(Remote_location)):
    if Remote_location[i] == 'Yes':
        Remote_location_clean[i] = 1
        
# print("International_clean:",International_clean)
# print("length of International_clean:",len(International_clean))

# print("Express_shipment_clean:",Express_shipment_clean)
# print("length of Express_shipment_clean:",len(Express_shipment_clean))

# print("Installation_included_clean:",Installation_included_clean)
# print("length of Installation_included_clean:",len(Installation_included_clean))

# print("Fragile_clean:",Fragile_clean)
# print("length of Fragile_clean:",len(Fragile_clean))

# print("Remote_location_clean",Remote_location_clean)
# print("length of Remote_location_clean:",len(Remote_location_clean))

International_clean: [1. 0. 0. ... 1. 0. 0.]
length of International_clean: 3362
Express_shipment_clean: [1. 0. 0. ... 1. 1. 1.]
length of Express_shipment_clean: 3362
Installation_included_clean: [0. 0. 0. ... 0. 0. 0.]
length of Installation_included_clean: 3362
Fragile_clean: [0. 0. 1. ... 0. 0. 0.]
length of Fragile_clean: 3362
Remote_location_clean [0. 0. 1. ... 1. 1. 0.]
length of Remote_location_clean: 3362


In [120]:
# Clean data

# Create dummy for Transport
Airways = np.zeros(len(Transport))
Roadways = np.zeros(len(Transport))
Waterways = np.zeros(len(Transport))


for i in range(len(Transport)):
    if Transport[i] == 'Airways':
        Airways[i] = 1
    elif Transport[i] == 'Roadways':
        Roadways[i] = 1
    else:
        Waterways[i] = 1
        
# print("Airways:",Airways)
# print("Length of Airways:",len(Airways))

# print("Roadways:",Roadways)
# print("Length of Roadways:",len(Roadways))

# print("Waterways:",Waterways)
# print("Length of Waterways:",len(Waterways))

Airways: [1. 0. 0. ... 1. 0. 1.]
Length of Airways: 3362
Roadways: [0. 1. 1. ... 0. 1. 0.]
Length of Roadways: 3362
Waterways: [0. 0. 0. ... 0. 0. 0.]
Length of Waterways: 3362


In [131]:
# Clean data

# Create dummy for Customer Information

# unique_CI = set(Customer_information)
# print(unique_CI)

Working_Class = np.zeros(len(Customer_information))
Wealthy = np.zeros(len(Customer_information))


for i in range(len(Customer_information)):
    if Customer_information[i] == 'Working Class':
        Working_Class[i] = 1
    else:
        Wealthy[i] = 1
print(Working_Class)
print(Wealthy)

[1. 1. 1. ... 0. 1. 1.]
[0. 0. 0. ... 1. 0. 0.]


In [135]:
# Clean data

# Create dummy for Customer_Location
# unique_CL = set(Customer_location)
# print(unique_CL)
#Since there are too many unique variables, we will not use them in regression.


In [137]:
# DATA FOR REGRESSION

# Artist_reputation
# Height
# Width
# Weight

# (Material) -> 
# Brass
# Clay
# Aluminium
# Wood
# Marble
# Bronze
# Stone 

# Price_of_sculpture
# Base_shipping_price
# International_clean
# Express_shipment_clean
# Installation_included_clean

# (Transport) ->
# Airways
# Roadways
# Waterways

# Fragile_clean

# (Customer Information) ->
# Working_Class
# Wealthy

#Remote_location_clean

#timeliness_of_a_shipping

In [167]:
x = np.stack((Artist_reputation, Height, Width, Weight, Brass,Clay,Aluminium,Wood,Marble,Bronze,Stone, Price_of_sculpture, Base_shipping_price,International_clean, Express_shipment_clean, Installation_included_clean, Airways, Roadways, Waterways, Fragile_clean, Working_Class, Wealthy, Remote_location_clean, timeliness_of_a_shipping), axis = 1) #axis = 1 connect horizontally (column by column)
y = Cost
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size = 0.2,random_state = 40)
#20 percent will be use for test #every one in this room will get equal result
print(x)

[[ 2.6e-01  1.7e+01  6.0e+00 ...  0.0e+00  0.0e+00 -4.0e+00]
 [ 2.8e-01  3.0e+00  3.0e+00 ...  0.0e+00  0.0e+00 -1.0e+00]
 [ 7.0e-02  8.0e+00  5.0e+00 ...  0.0e+00  1.0e+00 -1.0e+00]
 ...
 [ 3.7e-01  3.7e+01  1.0e+01 ...  1.0e+00  1.0e+00 -3.0e+00]
 [ 2.0e-02  3.3e+01  9.0e+00 ...  0.0e+00  1.0e+00  2.0e+00]
 [ 1.8e-01  3.0e+01  1.3e+01 ...  0.0e+00  0.0e+00  2.0e+00]]


In [168]:
print(len(x_train))
print(len(y_test))

2689
673


In [169]:
# Run the linear regression model
LR = LinearRegression()
LR.fit(x_train, y_train)
print('b0 = ' + "{:.4f}".format(LR.intercept_))
for i in range(len(LR.coef_)):
    print('b' + str(i+1) + ' = ' + "{:.4f}".format(LR.coef_[i]))# "{:.4f}" -> use 4 decimal places

b0 = -7108.0150
b1 = 13781.9295
b2 = 266.3960
b3 = -1106.7341
b4 = 0.0192
b5 = 4513.4061
b6 = -6322.5241
b7 = 3411.5008
b8 = 3919.4179
b9 = 3309.9897
b10 = 5212.6460
b11 = -14044.4362
b12 = 6.3293
b13 = -50.7314
b14 = 1204.1935
b15 = 3257.8184
b16 = -282.5124
b17 = 5219.7081
b18 = 0.0000
b19 = 71.2514
b20 = 9940.9645
b21 = 1067.4653
b22 = -1067.4653
b23 = -1920.9156
b24 = -183.0911


In [171]:
# Apply the model to the test set
y_prediction = LR.predict(x_test)
print(y_prediction)
print(y_test)

[-6.42815523e+03 -5.80322276e+03 -1.37895531e+03  1.39284994e+04
 -9.50840628e+03  8.29119234e+03  6.74852074e+04  1.56509482e+03
  7.30590384e+03  6.63777101e+03  7.31796221e+02  2.15253701e+03
  1.22856953e+04  7.47133804e+04 -2.05614203e+03 -1.12491858e+04
 -1.73764834e+04 -3.87860242e+03  1.00004569e+05  7.19521349e+03
  5.30450756e+03  6.70337426e+03  1.14582363e+05  3.92863282e+03
  2.22134625e+04 -1.34415461e+04 -1.35549540e+04  8.31858179e+02
 -7.06540060e+03  7.51048476e+05 -7.71611424e+03 -2.96374262e+02
  1.10030206e+03 -7.14697782e+03 -4.67987373e+03  9.60238598e+03
  1.20127504e+04  1.48515008e+03 -2.99229435e+03 -2.52413035e+04
 -3.53420057e+03  9.71509004e+04 -5.89215385e+03  5.56093212e+04
 -2.01450244e+04  6.79989112e+03  5.32300786e+03  1.09852446e+04
  5.51362351e+03  1.73449805e+03  8.27237371e+03  2.97129678e+03
  3.07565085e+03  6.18963934e+03  5.37580756e+03 -2.48964833e+03
 -9.42820996e+03 -1.65733747e+04 -3.45055134e+03 -3.17957587e+03
  9.21988303e+03 -1.99017

In [172]:
# Accuracy indicators
MSE = mean_squared_error(y_test, y_prediction)
RMSE = np.sqrt(MSE)
MAPE = mean_absolute_percentage_error(y_test, y_prediction)
print('RMSE: ' + "{:.4f}".format(RMSE))
print('MAPE: ' + "{:.4f}".format(MAPE*100)+'%')

RMSE: 220330.9273
MAPE: 1503.8704%
