In [62]:
import numpy as np
import csv
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error
import matplotlib.pyplot as plt
from datetime import datetime

In [36]:
with open('train.csv') as csv_file: # Make sure to replace 'train.csv' with your actual file path
    readCSV = csv.reader(csv_file)
    next(readCSV, None) # Skip the title of the csv file
    data1 = []
    for row in readCSV:
        data1.append(row)
print(len(data1))

6500


In [71]:
# with open('train.csv') as csv_file: #/Users/thanakornpongritsakda/Documents/Programming-SCMA-249/50_Startups.csv (path)
#     readCSV = csv.reader(csv_file)
#     next(readCSV, None) #skip the title of the csv file
#     data1 = []
#     for row in readCSV:
#         data1.append(row)
        
with open('train.csv') as csv_file: # Make sure to replace 'train.csv' with your actual file path
    readCSV = csv.reader(csv_file)
    next(readCSV, None) # Skip the title of the csv file
    data1 = []
    for row in readCSV:
        if "" not in row:  # This checks if 'NA' is not present in the row
            data1.append(row)

        
data1 = np.array(data1)
Artist_reputation = np.array(data1[:,2], dtype = np.float64)
Height = np.array(data1[:,3], dtype = np.float64)
Width = np.array(data1[:,4], dtype = np.float64)
Weight = np.array(data1[:,5], dtype = np.float64)
Material = np.array(data1[:,6])
Price_of_sculpture = np.array(data1[:,7], dtype = np.float64)
Base_shipping_price = np.array(data1[:,8], dtype = np.float64)
International = np.array(data1[:,9])
Express_shipment = np.array(data1[:,10])
Installation_included = np.array(data1[:,11])
Transport = np.array(data1[:,12])
Fragile = np.array(data1[:,13])
Customer_information = np.array(data1[:,14])
Remote_location = np.array(data1[:,15])
Scheduled_date = np.array(data1[:,16])
Delivery_date = np.array(data1[:,17])
Customer_location = np.array(data1[:,18])

# Define a function to convert date strings to datetime objects
def parse_dates(date_str):
    return datetime.strptime(date_str, '%m/%d/%y')  # Adjusted the format to match your dates

# Vectorize the function so it can be applied over numpy arrays
vectorized_parse_dates = np.vectorize(parse_dates)

# Convert the date strings to datetime objects
Scheduled_dates_parsed = vectorized_parse_dates(Scheduled_date)
Delivery_dates_parsed = vectorized_parse_dates(Delivery_date)

# Calculate the difference in days
timeliness_of_a_shipping = (Delivery_dates_parsed - Scheduled_dates_parsed).astype('timedelta64[D]').astype(int)
# Early Shipping: Represented as a negative number
# On-time Shipping: Represented as zero
# Late Shipping: Represented as a positive number

print(data1)
print(Artist_reputation)
print(Height)
print(Width)
print(Weight)
print(Material)
print(Price_of_sculpture)
print(Base_shipping_price)
print(International)
print(Express_shipment)
print(Installation_included)
print(Transport)
print(Fragile)
print(Customer_information)
print(Remote_location)
print(Scheduled_date)
print(Delivery_date)
print(Customer_location)
print(timeliness_of_a_shipping)

<class 'numpy.ndarray'>
[-4 -1 -1 ... -3  2  2]


In [81]:
# Clean data

# Create dummy for Material
Brass = np.zeros(len(Material))
Clay = np.zeros(len(Material))
Aluminium = np.zeros(len(Material))
Wood = np.zeros(len(Material))
Marble = np.zeros(len(Material))
Bronze = np.zeros(len(Material))
Stone = np.zeros(len(Material))

for i in range(len(Material)):
    if Material[i] == 'Brass':
        Brass[i] = 1
    elif Material[i] == 'Clay':
        Clay[i] = 1
    elif Material[i] == 'Aluminium':
        Aluminium[i] = 1
    elif Material[i] == 'Wood':
        Wood[i] = 1
    elif Material[i] == 'Marble':
        Marble[i] = 1
    elif Material[i] == 'Bronze':
        Bronze[i] = 1
    else:
        Stone[i] = 1

print(Brass)
print(Clay)
print(Aluminium)
print(Wood)
print(Marble)
print(Bronze)
print(len(Stone))
#print(len(State))

[1. 1. 0. ... 1. 0. 1.]
[0. 0. 1. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
3362
