In [1]:
import numpy as np
import csv
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error
import matplotlib.pyplot as plt
from datetime import datetime
from sklearn.metrics import r2_score

In [2]:
with open('train.csv') as csv_file: # Make sure to replace 'train.csv' with your actual file path
    readCSV = csv.reader(csv_file)
    next(readCSV, None) # Skip the title of the csv file
    data1 = []
    for row in readCSV:
        data1.append(row)
print(len(data1))

6500


In [4]:
# with open('train.csv') as csv_file: #/Users/thanakornpongritsakda/Documents/Programming-SCMA-249/50_Startups.csv (path)
#     readCSV = csv.reader(csv_file)
#     next(readCSV, None) #skip the title of the csv file
#     data1 = []
#     for row in readCSV:
#         data1.append(row)
        
with open('train.csv') as csv_file: # Make sure to replace 'train.csv' with your actual file path
    readCSV = csv.reader(csv_file)
    next(readCSV, None) # Skip the title of the csv file
    data1 = []
    for row in readCSV:
        if "" not in row:  # This checks if 'NA' is not present in the row
            data1.append(row)

        
data1 = np.array(data1)
Artist_reputation = np.array(data1[:,2], dtype = np.float64)
Height = np.array(data1[:,3], dtype = np.float64)
Width = np.array(data1[:,4], dtype = np.float64)
Weight = np.array(data1[:,5], dtype = np.float64)
Material = np.array(data1[:,6])
Price_of_sculpture = np.array(data1[:,7], dtype = np.float64)
Base_shipping_price = np.array(data1[:,8], dtype = np.float64)
International = np.array(data1[:,9])
Express_shipment = np.array(data1[:,10])
Installation_included = np.array(data1[:,11])
Transport = np.array(data1[:,12])
Fragile = np.array(data1[:,13])
Customer_information = np.array(data1[:,14])
Remote_location = np.array(data1[:,15])
Scheduled_date = np.array(data1[:,16])
Delivery_date = np.array(data1[:,17])
Customer_location = np.array(data1[:,18])
Cost = np.abs(data1[:, 19].astype(np.float64))

Size = Width * Height


# Define a function to convert date strings to datetime objects
def parse_dates(date_str):
    return datetime.strptime(date_str, '%m/%d/%y')  # Adjusted the format to match your dates

# Vectorize the function so it can be applied over numpy arrays
vectorized_parse_dates = np.vectorize(parse_dates)

# Convert the date strings to datetime objects
Scheduled_dates_parsed = vectorized_parse_dates(Scheduled_date)
Delivery_dates_parsed = vectorized_parse_dates(Delivery_date)

# Calculate the difference in days
timeliness_of_a_shipping = (Delivery_dates_parsed - Scheduled_dates_parsed).astype('timedelta64[D]').astype(int)
# Early Shipping: Represented as a negative number
# On-time Shipping: Represented as zero
# Late Shipping: Represented as a positive number

# print(data1)
# print(Artist_reputation)
# print(Height)
# print(Width)
# print(Weight)
# print(Material)
# print(Price_of_sculpture)
# print(Base_shipping_price)
# print(International)
# print(Express_shipment)
# print(Installation_included)
# print(Transport)
# print(Fragile)
# print(Customer_information)
# print(Remote_location)
# print(Scheduled_date)
# print(Delivery_date)
# print(Customer_location)
# print(timeliness_of_a_shipping)

In [5]:
# Clean data

# Create dummy for Material
Brass = np.zeros(len(Material))
Clay = np.zeros(len(Material))
Aluminium = np.zeros(len(Material))
Wood = np.zeros(len(Material))
Marble = np.zeros(len(Material))
Bronze = np.zeros(len(Material))
Stone = np.zeros(len(Material))

for i in range(len(Material)):
    if Material[i] == 'Brass':
        Brass[i] = 1
    elif Material[i] == 'Clay':
        Clay[i] = 1
    elif Material[i] == 'Aluminium':
        Aluminium[i] = 1
    elif Material[i] == 'Wood':
        Wood[i] = 1
    elif Material[i] == 'Marble':
        Marble[i] = 1
    elif Material[i] == 'Bronze':
        Bronze[i] = 1
    else:
        Stone[i] = 1

# print(Brass)
# print(Clay)
# print(Aluminium)
# print(Wood)
# print(Marble)
# print(Bronze)
# print(len(Stone))
# print(len(State))

[1. 1. 0. ... 1. 0. 1.]
[0. 0. 1. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
3362


In [6]:
# Clean data for International, Express Shipment, Installation Included, Fragile and Remote Location
International_clean = np.zeros(len(International))
for i in range(len(International)):
    if International[i] == 'Yes':
        International_clean[i] = 1

Express_shipment_clean = np.zeros(len(Express_shipment))
for i in range(len(Express_shipment)):
    if Express_shipment[i] == 'Yes':
        Express_shipment_clean[i] = 1
        
Installation_included_clean = np.zeros(len(Installation_included))
for i in range(len(Installation_included)):
    if Installation_included[i] == 'Yes':
        Installation_included_clean[i] = 1
        
Fragile_clean = np.zeros(len(Fragile))
for i in range(len(Fragile)):
    if Fragile[i] == 'Yes':
        Fragile_clean[i] = 1
        
Remote_location_clean = np.zeros(len(Remote_location))
for i in range(len(Remote_location)):
    if Remote_location[i] == 'Yes':
        Remote_location_clean[i] = 1
        
# print("International_clean:",International_clean)
# print("length of International_clean:",len(International_clean))

# print("Express_shipment_clean:",Express_shipment_clean)
# print("length of Express_shipment_clean:",len(Express_shipment_clean))

# print("Installation_included_clean:",Installation_included_clean)
# print("length of Installation_included_clean:",len(Installation_included_clean))

# print("Fragile_clean:",Fragile_clean)
# print("length of Fragile_clean:",len(Fragile_clean))

# print("Remote_location_clean",Remote_location_clean)
# print("length of Remote_location_clean:",len(Remote_location_clean))

In [7]:
# Clean data

# Create dummy for Transport
Airways = np.zeros(len(Transport))
Roadways = np.zeros(len(Transport))
Waterways = np.zeros(len(Transport))


for i in range(len(Transport)):
    if Transport[i] == 'Airways':
        Airways[i] = 1
    elif Transport[i] == 'Roadways':
        Roadways[i] = 1
    else:
        Waterways[i] = 1
        
# print("Airways:",Airways)
# print("Length of Airways:",len(Airways))

# print("Roadways:",Roadways)
# print("Length of Roadways:",len(Roadways))

# print("Waterways:",Waterways)
# print("Length of Waterways:",len(Waterways))

In [8]:
# Clean data

# Create dummy for Customer Information

# unique_CI = set(Customer_information)
# print(unique_CI)

Working_Class = np.zeros(len(Customer_information))
Wealthy = np.zeros(len(Customer_information))

for i in range(len(Customer_information)):
    if Customer_information[i] == 'Working Class':
        Working_Class[i] = 1
    else:
        Wealthy[i] = 1
print(Working_Class)
print(Wealthy)

[1. 1. 1. ... 0. 1. 1.]
[0. 0. 0. ... 1. 0. 0.]


In [183]:
# Clean data

# Create dummy for Customer_Location
# unique_CL = set(Customer_location)
# print(unique_CL)
#Since there are too many unique variables, we will not use them in regression.


In [68]:
# DATA FOR REGRESSION

# Artist_reputation
# Height
# Width
# Weight

# (Material) -> 
# Brass
# Clay
# Aluminium
# Wood
# Marble
# Bronze
# Stone 

# Price_of_sculpture
# Base_shipping_price
# International_clean
# Express_shipment_clean
# Installation_included_clean

# (Transport) ->
# Airways
# Roadways
# Waterways

# Fragile_clean

# (Customer Information) ->
# Working_Class
# Wealthy

#Remote_location_clean

#timeliness_of_a_shipping

a = Artist_reputation
b = Height
c = Width
d = Weight
# e = Brass
# f = Clay
# g = Aluminium
# h = Wood
# i1 = Marble
# j1 = Bronze
# k = Stone 
l = Price_of_sculpture
m = Base_shipping_price
n = International_clean
o = Express_shipment_clean
p = Installation_included_clean
q = Airways
r = Roadways
s = Waterways
t = Fragile_clean
u = Working_Class
v = Wealthy
w = Remote_location_clean
x1 = timeliness_of_a_shipping

In [21]:
x = np.stack((Artist_reputation, Size, Weight, Price_of_sculpture, Base_shipping_price), axis = 1) #axis = 1 connect horizontally (column by column)
y = Cost
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size = 0.2,random_state = 52)
#20 percent will be use for test #every one in this room will get equal result
print(x)

[[2.600000e-01 1.020000e+02 4.128000e+03 1.391000e+01 1.627000e+01]
 [2.800000e-01 9.000000e+00 6.100000e+01 6.830000e+00 1.500000e+01]
 [7.000000e-02 4.000000e+01 2.370000e+02 4.960000e+00 2.118000e+01]
 ...
 [3.700000e-01 3.700000e+02 1.655100e+04 2.828000e+01 3.846000e+01]
 [2.000000e-02 2.970000e+02 1.269377e+06 2.929130e+03 6.976000e+01]
 [1.800000e-01 3.900000e+02 3.472900e+04 4.663000e+01 7.825000e+01]]


In [22]:
print(len(x_train))
print(len(y_test))

2689
673


In [23]:
# Run the linear regression model
LR = LinearRegression()
LR.fit(x_train, y_train)
print('b0 = ' + "{:.4f}".format(LR.intercept_))
for i in range(len(LR.coef_)):
    print('b' + str(i+1) + ' = ' + "{:.4f}".format(LR.coef_[i]))# "{:.4f}" -> use 4 decimal places

b0 = -18275.7246
b1 = 19806.2024
b2 = 50.7259
b3 = -0.0302
b4 = 16.7262
b5 = 38.9637


In [24]:
# Apply the model to the test set
y_prediction = LR.predict(x_test)
print(y_prediction)
print(y_test)

[-1.75079736e+03 -1.76726258e+04 -1.43776886e+03  6.24854528e+04
  8.00988708e+03  1.81436068e+04  1.18454985e+04 -7.39744931e+03
  1.40322546e+04 -8.21673773e+03  1.57124079e+04  1.04156793e+05
 -5.52185692e+02 -4.96880805e+03  5.73145359e+03 -8.74203372e+03
 -5.46482052e+03  5.23906696e+04  2.27115076e+03  1.78813546e+05
 -2.91120034e+03  2.28799026e+03  6.08111904e+03 -2.02650906e+03
  1.44296151e+04 -4.74934541e+03 -3.99542631e+03 -9.20138357e+02
  1.90124819e+04  2.10307595e+04  7.47890455e+03  2.70911559e+04
 -1.31275760e+04  1.30074344e+04  1.01789590e+05 -1.27109253e+04
  9.05589127e+04 -6.24330690e+03 -1.08349472e+04  1.17874586e+03
  2.36366156e+04 -1.27534314e+03  2.75499781e+03  4.76696859e+04
 -1.26746597e+04 -5.40807586e+03 -1.22593230e+04  6.50194418e+02
 -2.72634578e+03 -1.07996480e+04  1.01432207e+04  8.09969141e+04
 -1.10566894e+04 -5.04355165e+03  2.61992943e+03 -1.46611590e+04
  9.84491883e+03  3.38121784e+04  1.04757620e+04 -4.49621464e+03
 -4.81531978e+03 -9.61997

In [25]:
# Accuracy indicators
MSE = mean_squared_error(y_test, y_prediction)
RMSE = np.sqrt(MSE)
MAPE = mean_absolute_percentage_error(y_test, y_prediction)
print('RMSE: ' + "{:.4f}".format(RMSE))
print('MAPE: ' + "{:.4f}".format(MAPE*100)+'%')

RMSE: 153097.6051
MAPE: 2384.7090%


In [15]:
model = LinearRegression()
model.fit(x_train, y_train)

# Step 2: Predict on test data
y_pred = model.predict(x_test)

# Step 3: Calculate R-squared
r_squared = r2_score(y_test, y_pred)

# Step 4: Calculate the number of observations and predictors
n = x_test.shape[0]  # Number of observations in the test set
p = x.shape[1]       # Number of predictors (features)

# Step 5: Calculate Adjusted R-squared
adjusted_r_squared = 1 - (1 - r_squared) * (n - 1) / (n - p - 1)
print(f'Adjusted R-squared value: {adjusted_r_squared}')
print(f'R-squared value: {r_squared}')

Adjusted R-squared value: 0.5702475594152558
R-squared value: 0.5734451222172257


In [27]:
# # Scatter plot of true vs predicted values
# plt.scatter(y_test, y_prediction)
# plt.xlabel('True Values')
# plt.ylabel('Predictions')
# plt.title('True Values vs Predictions')
# plt.show()

In [26]:
# # Improved scatter plot
# plt.figure(figsize=(10, 8))  # Larger figure size
# plt.scatter(y_test, y_prediction, alpha=0.5)  # Semi-transparent points

# # Adding a line of perfect prediction for reference
# plt.plot([0, max(y_test)], [0, max(y_test)], 'k--', lw=2)

# plt.xlabel('True Values [Units]', fontsize=14)  # Descriptive label with font size
# plt.ylabel('Predictions [Units]', fontsize=14)  # Descriptive label with font size
# plt.title('Improved Scatter Plot of True Values vs Predictions', fontsize=16)  # Descriptive title with font size
# plt.tick_params(axis='both', which='major', labelsize=12)  # Larger tick labels

# # Adding grid lines
# plt.grid(True, which='both', linestyle='--', linewidth=0.5)

# # Tight layout often produces a nicer plot
# plt.tight_layout()

# # Show the plot
# plt.show()

In [72]:
with open('train.csv') as csv_file: # Make sure to replace 'train.csv' with your actual file path
    readCSV = csv.reader(csv_file)
    next(readCSV, None) # Skip the title of the csv file
    data1 = []
    for row in readCSV:
        data1.append(row)
# print(len(data1))

# with open('train.csv') as csv_file: #/Users/thanakornpongritsakda/Documents/Programming-SCMA-249/50_Startups.csv (path)
#     readCSV = csv.reader(csv_file)
#     next(readCSV, None) #skip the title of the csv file
#     data1 = []
#     for row in readCSV:
#         data1.append(row)
        
with open('train.csv') as csv_file: # Make sure to replace 'train.csv' with your actual file path
    readCSV = csv.reader(csv_file)
    next(readCSV, None) # Skip the title of the csv file
    data1 = []
    for row in readCSV:
        if "" not in row:  # This checks if 'NA' is not present in the row
            data1.append(row)

        
data1 = np.array(data1)
Artist_reputation = np.array(data1[:,2], dtype = np.float64)
Height = np.array(data1[:,3], dtype = np.float64)
Width = np.array(data1[:,4], dtype = np.float64)
Weight = np.array(data1[:,5], dtype = np.float64)
Material = np.array(data1[:,6])
Price_of_sculpture = np.array(data1[:,7], dtype = np.float64)
Base_shipping_price = np.array(data1[:,8], dtype = np.float64)
International = np.array(data1[:,9])
Express_shipment = np.array(data1[:,10])
Installation_included = np.array(data1[:,11])
Transport = np.array(data1[:,12])
Fragile = np.array(data1[:,13])
Customer_information = np.array(data1[:,14])
Remote_location = np.array(data1[:,15])
Scheduled_date = np.array(data1[:,16])
Delivery_date = np.array(data1[:,17])
Customer_location = np.array(data1[:,18])
Cost = np.abs(data1[:, 19].astype(np.float64))

Size = Width * Height


# Define a function to convert date strings to datetime objects
def parse_dates(date_str):
    return datetime.strptime(date_str, '%m/%d/%y')  # Adjusted the format to match your dates

# Vectorize the function so it can be applied over numpy arrays
vectorized_parse_dates = np.vectorize(parse_dates)

# Convert the date strings to datetime objects
Scheduled_dates_parsed = vectorized_parse_dates(Scheduled_date)
Delivery_dates_parsed = vectorized_parse_dates(Delivery_date)

# Calculate the difference in days
timeliness_of_a_shipping = (Delivery_dates_parsed - Scheduled_dates_parsed).astype('timedelta64[D]').astype(int)
# Early Shipping: Represented as a negative number
# On-time Shipping: Represented as zero
# Late Shipping: Represented as a positive number
# Clean data

# Create dummy for Material
Brass = np.zeros(len(Material))
Clay = np.zeros(len(Material))
Aluminium = np.zeros(len(Material))
Wood = np.zeros(len(Material))
Marble = np.zeros(len(Material))
Bronze = np.zeros(len(Material))
Stone = np.zeros(len(Material))

for i in range(len(Material)):
    if Material[i] == 'Brass':
        Brass[i] = 1
    elif Material[i] == 'Clay':
        Clay[i] = 1
    elif Material[i] == 'Aluminium':
        Aluminium[i] = 1
    elif Material[i] == 'Wood':
        Wood[i] = 1
    elif Material[i] == 'Marble':
        Marble[i] = 1
    elif Material[i] == 'Bronze':
        Bronze[i] = 1
    else:
        Stone[i] = 1

# print(Brass)
# print(Clay)
# print(Aluminium)
# print(Wood)
# print(Marble)
# print(Bronze)
# print(len(Stone))
# print(len(State))

# Clean data for International, Express Shipment, Installation Included, Fragile and Remote Location
International_clean = np.zeros(len(International))
for i in range(len(International)):
    if International[i] == 'Yes':
        International_clean[i] = 1

Express_shipment_clean = np.zeros(len(Express_shipment))
for i in range(len(Express_shipment)):
    if Express_shipment[i] == 'Yes':
        Express_shipment_clean[i] = 1
        
Installation_included_clean = np.zeros(len(Installation_included))
for i in range(len(Installation_included)):
    if Installation_included[i] == 'Yes':
        Installation_included_clean[i] = 1
        
Fragile_clean = np.zeros(len(Fragile))
for i in range(len(Fragile)):
    if Fragile[i] == 'Yes':
        Fragile_clean[i] = 1
        
Remote_location_clean = np.zeros(len(Remote_location))
for i in range(len(Remote_location)):
    if Remote_location[i] == 'Yes':
        Remote_location_clean[i] = 1
        
# print("International_clean:",International_clean)
# print("length of International_clean:",len(International_clean))

# print("Express_shipment_clean:",Express_shipment_clean)
# print("length of Express_shipment_clean:",len(Express_shipment_clean))

# print("Installation_included_clean:",Installation_included_clean)
# print("length of Installation_included_clean:",len(Installation_included_clean))

# print("Fragile_clean:",Fragile_clean)
# print("length of Fragile_clean:",len(Fragile_clean))

# print("Remote_location_clean",Remote_location_clean)
# print("length of Remote_location_clean:",len(Remote_location_clean))

# Clean data

# Create dummy for Transport
Airways = np.zeros(len(Transport))
Roadways = np.zeros(len(Transport))
Waterways = np.zeros(len(Transport))


for i in range(len(Transport)):
    if Transport[i] == 'Airways':
        Airways[i] = 1
    elif Transport[i] == 'Roadways':
        Roadways[i] = 1
    else:
        Waterways[i] = 1
        
# print("Airways:",Airways)
# print("Length of Airways:",len(Airways))

# print("Roadways:",Roadways)
# print("Length of Roadways:",len(Roadways))

# print("Waterways:",Waterways)
# print("Length of Waterways:",len(Waterways))

# Clean data

# Create dummy for Customer Information

# unique_CI = set(Customer_information)
# print(unique_CI)

Working_Class = np.zeros(len(Customer_information))
Wealthy = np.zeros(len(Customer_information))

for i in range(len(Customer_information)):
    if Customer_information[i] == 'Working Class':
        Working_Class[i] = 1
    else:
        Wealthy[i] = 1
print(Working_Class)
print(Wealthy)

x = np.stack((l,m,p), axis = 1) #axis = 1 connect horizontally (column by column)
y = Cost
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size = 0.2,random_state = 52)
#20 percent will be use for test #every one in this room will get equal result
# print(x)

# Run the linear regression model
LR = LinearRegression()
LR.fit(x_train, y_train)
print('b0 = ' + "{:.4f}".format(LR.intercept_))
for i in range(len(LR.coef_)):
    print('b' + str(i+1) + ' = ' + "{:.4f}".format(LR.coef_[i]))# "{:.4f}" -> use 4 decimal places
    
# Apply the model to the test set
y_prediction = LR.predict(x_test)
# print(y_prediction)
# print(y_test)

# Accuracy indicators
MSE = mean_squared_error(y_test, y_prediction)
RMSE = np.sqrt(MSE)
MAPE = mean_absolute_percentage_error(y_test, y_prediction)
print('RMSE: ' + "{:.4f}".format(RMSE))
print('MAPE: ' + "{:.4f}".format(MAPE*100)+'%')

[1. 1. 1. ... 0. 1. 1.]
[0. 0. 0. ... 1. 0. 0.]
b0 = -1067.7061
b1 = 8.8143
b2 = 114.5555
b3 = 262.4320
RMSE: 129618.0047
MAPE: 463.9867%


In [75]:
from itertools import combinations
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_percentage_error

# Assuming 'a' through 'x1' are your independent variables and 'y' is the dependent variable
variables = [a, b, c, d, e, f, g, h, i1, j1, k, l, m, n, o, p, q, r, s, t, u, v, w, x1]
y = Cost  # Replace with your actual dependent variable data

# Splitting the dataset into training and testing sets
x_train_full, x_test_full, y_train, y_test = train_test_split(np.stack(variables, axis=1), y, test_size=0.2, random_state=52)

# To store the best combination and its error
best_combination = None
lowest_mape = float('inf')

# Iterate over all possible combinations of the independent variables
for i in range(1, len(variables) + 1):
    for combo in combinations(range(len(variables)), i):
        # Selecting the columns for the current combination
        x_train = x_train_full[:, combo]
        x_test = x_test_full[:, combo]

        # Train the linear regression model
        LR = LinearRegression()
        LR.fit(x_train, y_train)

        # Predict and calculate MAPE
        y_prediction = LR.predict(x_test)
        mape = mean_absolute_percentage_error(y_test, y_prediction)

        # Check if this combination gives a lower MAPE
        if mape < lowest_mape:
            lowest_mape = mape
            best_combination = combo

# Print the best combination and its MAPE
print("Best Combination:", best_combination)
print("Lowest MAPE:", lowest_mape)


KeyboardInterrupt: 